# CC24 Backend Dockerfile
FROM node:20-alpine

# Install dependencies for Sharp
RUN apk add --no-cache python3 make g++ vips-dev

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 8000

CMD ["npm", "start"]
